### ISSUE TITLE
Multi-targeting host build to create .NET 8 artifacts

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#10044]
Update the in-proc host to add a .NET 8 target.

Feature branch: https://github.com/Azure/azure-functions-host/tree/feature/in-proc8

```[tasklist]
### Tasks
- [x] Review and merge PR #9858
- [x] Create feature branch (from in-proc) for new .NET 8 changes
- [x] Backport 9858 to in-proc (PR #10079)
- [x] Update runtime assembly files in dev and in-proc branch
- [x] Address any issues and failures in .NET 8 in-proc branch
```

```[tasklist]
### Test Failures
- [x] DependencyTests - Need to update file path (different test for net6.0 vs net8.0)
- [x] RpcWorkerConfigFactoryTests - Unexpected process count (my machines core count is 16 which is impacting this test, might be fine in the CI pipeline)
- [x] ProxyFunctionDescriptorProviderTests - Call is ambiguous between the following methods or properties
- [x] ProxyFunctionDescriptorTests - Call is ambiguous between the following methods or properties
- [x] WebFunctionsManagerTests - MoqException: IConfiguration
- [x] DefaultDependencyValidatorTests - DryIoc.ContainerException
- [x] LoggingConfigurationTests - DryIoc.ContainerException
- [x] NullReference and ArgumentNull exceptions
- [x] TFM error
- [x] FunctionAssemblyLoadContextEndToEndTests failures
- [x] Missing debug_net6.0 dir in pipeline
```

**Comment by fabiocav** [comment]
Closing as resolved.
