### ISSUE TITLE
Migrate Microsoft.Azure.Cosmos.Tables to Azure.Data.Tables

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-host#10129]
`Microsoft.Azure.Cosmos.Tables` is depracated. We should migrate usage of this package in the WebHost over to `Azure.Data.Tables`.  Migration guide can be found here: [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/MigrationGuide.md).
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-functions-host/issues/10165
- [ ] https://github.com/Azure/azure-functions-host/issues/10166
- [ ] https://github.com/Azure/azure-functions-host/issues/10354
```
