### ISSUE TITLE
Address flaky unit tests

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-host#10135]
Using this issue to track flaky unit tests as they are discovered.

## Flaky tests

| Fix PR | Test | Failed Run |
| - | - | - |
| #10128 | https://github.com/Azure/azure-functions-host/blob/1bf081347aa0ff3fa02e846802ae330611d192ff/test/WebJobs.Script.Tests/FileMonitoringServiceTests.cs#L286 | N/A | 
| TBD | https://github.com/Azure/azure-functions-host/blob/1bf081347aa0ff3fa02e846802ae330611d192ff/test/WebJobs.Script.Tests/Security/SecretManagerTests.cs#L938 | [Failed run](https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=165675&view=logs&j=d090b295-8b65-5b33-df45-4b0e4ec519f8&t=c74105ee-1189-504a-7f57-81aa2e7f3871&s=96ac2280-8cb4-5df5-99de-dd2da759617d) |
| #10145 | https://github.com/Azure/azure-functions-host/blob/1bf081347aa0ff3fa02e846802ae330611d192ff/test/WebJobs.Script.Tests/Workers/Http/HttpFunctionInvocationDispatcherTests.cs#L23 | [Failed run](https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=165720&view=logs&jobId=d090b295-8b65-5b33-df45-4b0e4ec519f8&j=d090b295-8b65-5b33-df45-4b0e4ec519f8&t=c74105ee-1189-504a-7f57-81aa2e7f3871) |
| #10146 | https://github.com/Azure/azure-functions-host/blob/1bf081347aa0ff3fa02e846802ae330611d192ff/test/WebJobs.Script.Tests/FunctionsSyncServiceTests.cs#L18 |
| TBD | https://github.com/Azure/azure-functions-host/blob/1bf081347aa0ff3fa02e846802ae330611d192ff/test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/WebJobsStartupEndToEndTests.cs |
| TBD | https://github.com/Azure/azure-functions-host/blob/d223fa7a6f5a0265c5ba105d278b1d74432bfa65/test/WebJobs.Script.Tests/StartupContextProviderTests.cs#L77 | [Failed run](https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=166235&view=logs&jobId=d090b295-8b65-5b33-df45-4b0e4ec519f8&j=d090b295-8b65-5b33-df45-4b0e4ec519f8&t=025cb30c-0e76-583b-4c09-82a3c0dd90c6) |
| TBD | https://github.com/Azure/azure-functions-host/blob/633e2c05d31acadfa95bc347511fd8f7bfb1e312/test/WebJobs.Script.Tests/Workers/Rpc/GrpcWorkerChannelTests.cs#L251 | [Failed run](https://dev.azure.com/azfunc/internal/_build/results?buildId=171335&view=ms.vss-test-web.build-test-results-tab&runId=1409309&resultId=101930&paneView=debug) |

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-functions-host/pull/10145
- [ ] https://github.com/Azure/azure-functions-host/pull/10128
- [ ] https://github.com/Azure/azure-functions-host/pull/10146
- [ ] https://github.com/Azure/azure-functions-host/pull/10152
- [ ] https://github.com/Azure/azure-functions-host/pull/10172
```

**Comment by kshyju** [comment]
Few more from a recent [build](https://github.com/Azure/azure-functions-host/pull/10273/checks?check_run_id=27190359006).

1. Microsoft.Azure.WebJobs.Script.Tests.EndToEnd.NodeEndToEndTests.MultipleOutputs
2. Microsoft.Azure.WebJobs.Script.Tests.NodeScriptHostTests.ExecutionContext_IsProvided
3. Microsoft.Azure.WebJobs.Script.Tests.EndToEnd.SamplesEndToEndTests_Node_MultipleProcesses.NodeProcess_Different_AfterHostRestart

**Comment by kshyju** [comment]
1. Microsoft.Azure.WebJobs.Script.Tests.Configuration.FunctionsHostingConfigOptionsTest.Case_Insensitive
2. Microsoft.Azure.WebJobs.Script.Tests.Diagnostics.LinuxContainerEventGeneratorWithConsoleOutputTests.MultipleEventsBuffered

**Comment by kshyju** [comment]
Microsoft.Azure.WebJobs.Script.Tests.EndToEnd.SamplesEndToEndTests_Node_MultipleProcesses.NodeProcessCount_RemainsSame_AfterMultipleTimeouts

**Comment by jviau** [comment]
Closing this in favor of a new issue.
