### ISSUE TITLE
[Placeholder]Node.js Placeholders

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4511]
We need to move the scope of the node.js worker's startup so that it can run in placeholder mode. 

And this special casing must be done for Node.js placeholders to not have a bug: https://github.com/Azure/azure-functions-host/issues/4488

1. Whitelist node (Windows and Linux) https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/RpcInitializationService.cs#L30 https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/RpcInitializationService.cs#L34
2. Cache node version (`WEBSITE_DEFAULT_NODE_VERSION` from App Settings) in Placeholder mode to be accessed later. Probably best here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/WebHostLanguageWorkerChannelManager.cs (backup: check with Brett if this is ok) https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Standby/StandbyOptions.cs  https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Standby/StandbyOptionsSetup.cs
3. Update logic for IsSupportedRuntime to figure out if we should kill placeholder node.exe https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L176
4. Run from zip only? (Verify if Portal editing will work.)

Test:
- Going through Placeholders
- Not going through Placeholders
- x64 and x86 tests (Placeholders only apply for x86)
- Node 8 vs 10
    - Node 10.0.0 (not latest) - no placeholders
    - Node ~10 (placeholder) and ~8 (no placeholder)
    - Node exact match for latest (10.15.2, placeholder)
- With / without RUN_FROM_PACKAGE

------------------------------
Breakdown of issues:
- [x] Empty value environment variables - https://github.com/Azure/azure-functions-host/issues/4488
- [x] Implement node message types - https://github.com/Azure/azure-functions-nodejs-worker/issues/184
- [x] Whitelist node placeholders - https://github.com/Azure/azure-functions-host/issues/4713
- [ ] Placeholders without Run From Zip - https://github.com/Azure/azure-functions-host/issues/4534
- [ ] Clean up usage of IsPlaceholderModeEnabled and InStandbyMode - https://github.com/Azure/azure-functions-host/issues/4368
- [x] Test - https://github.com/Azure/azure-functions-host/issues/4712

**Comment by pragnagopa** [comment]
Changes needed:
- White list nodejs here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/RpcInitializationService.cs
- During specialization, update FunctionDispatcher to check for RunFromZip and verify WEBSITE_NODE_DEFAULT_VERSION is same as the placeholder version
  - If both conditions satisfy, use the placeholder process
  - If not, kill placeholder channels and continue with setting up the process within the JobHost.

**Comment by pragnagopa** [comment]
Adding more details on the picking node version 
- Host needs to know what is the latest node 10 version on
  - Antares for windows apps
  - Linux for linux consumption apps
- Placeholder node.exe  will be used only if WEBSITE_NODE_DEFAULT_VERSION  is an exact match with the current node 10 latest version .

@mhoeger  - Let me know if you have any further questions.

**Comment by pragnagopa** [comment]
Adding more details on how to get the latest version of node

- Placeholder template site has, `WEBSITE_NODE_DEFAULT_VERSION` is set to ~10
- Cache value of `WEBSITE_NODE_DEFAULT_VERSION` during placeholder mode
- During specialization look for exact match,

**Comment by mhoeger** [comment]
https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L176

**Comment by fabiocav** [comment]
@mhoeger moving this to Epics, can you please break this up and create the tasks we need to track?

**Comment by fabiocav** [comment]
Blocked on ANT83

**Comment by fabiocav** [comment]
Closing stale issue.
