### ISSUE TITLE
Epic to track Project Stein GA work from Host side

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#8848]
Epic to track the initial set of work needed for Project Stein GA from Host side. 

- [x] (Design) https://github.com/Azure/azure-functions-host/issues/8614
- [x] https://github.com/Azure/azure-functions-host/issues/8302
- [x] https://github.com/Azure/azure-functions-host/issues/8847
- [x] https://github.com/Azure/azure-functions-host/issues/8870

**Comment by surgupta-msft** [comment]
Closing as above tasks are completed from Host side. Will create new issues as needed.
