### ISSUE TITLE
FunctionsNetHost artifact cleanup

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#9953]
```[tasklist]
### Tasks
- [x] Move FunctionsNetHost pdb & dbg to symbols package.
- [x] Remove Linux artifacts from site extension.
- [ ] Update docker images to remove windows artifacts.
```

Change should go to dev and must be backported to in-proc branch.
